## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [26]:
df = pd.read_excel("csec_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58%,Critical,8 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67%,Critical,4 more,2026-10-07,1
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0%,Critical,36 more,Never,12

#### Section 1: Data Inspection

In [ ]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
print("First 10 rows:")
display(df.head(10))
print("\nShape of the data (Rows, Columns):")
print(df.shape)
print("\nData types of each column:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
5,4MW24CS128,SAMRUDDI,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
6,4MW24CS130,SANEEYA ALKIN RIZA,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
7,4MW24CS131,SANJANA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
8,4MW24CS132,SANYA,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25%,Critical,24 more,2026-09-25,3

Shape of the data (Rows, Columns):
(65, 12)

Data types of each column:
Roll No                 object
Student Name            object
Subject                 object
Total Classes            int64
Present                  int64
Absent                   int64
Excused                  int64
Attendance %            object
Status                  object
Classes Needed (75%)    object
Last Present Date       object
Consecutive Absences     int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """

#-----------------------------Write Solution Code-----------------------------
print("Missing Values Count:\n", df.isnull().sum())

Missing Values Count:
 Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = (
    df.columns.str.lower()
    .str.replace(" ", "_")
    .str.replace("%", "pct")
    .str.replace("(", "")
    .str.replace(")", "")
)
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [ ]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------

df["attendance_pct"] = (
    df["attendance_pct"].astype(str).str.replace("%", "").astype(float)
)
df["last_present_date"] = pd.to_datetime(
    df["last_present_date"], errors="coerce"
)
df[["attendance_pct", "last_present_date"]].head()

   attendance_pct last_present_date
0           100.0        2026-10-09
1            92.0        2026-10-07
2            17.0        2026-09-25
3            75.0        2026-10-09
4            83.0        2026-10-07

#### Section 2: Filtering & Selection

In [7]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical_students = df[df["status"] == "Critical"].sort_values(
    by="attendance_pct", ascending=True
)
critical_students.head()

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10

In [8]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
zero_present = df[df["present"] == 0]
zero_present[["roll_no", "student_name", "consecutive_absences"]]

       roll_no        student_name  consecutive_absences
20  4MW24CS144  SHREEHARI SHENOY R                    12
43  4MW24CS167             SURAJ R                    12
64  4MW25CS409            YASHVITH                    12

In [9]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
safe_students = df.loc[df["status"] == "Safe"]
subset_iloc = df.iloc[:15, 2:7]
display(safe_students.head())
display(subset_iloc)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-07,1
5,4MW24CS128,SAMRUDDI,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
6,4MW24CS130,SANEEYA ALKIN RIZA,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0
7,4MW24CS131,SANJANA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0

,subject,total_classes,present,absent,excused
0,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0
1,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
2,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0
3,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0
4,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0
5,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
6,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
7,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0
8,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0
9,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0
10,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0
11,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0
12,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0
13,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0
14,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0

In [10]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
high_absence = df[df["consecutive_absences"] >= 5]
high_absence[["student_name", "status", "last_present_date"]]

          student_name    status last_present_date
20  SHREEHARI SHENOY R  Critical               NaT
43             SURAJ R  Critical               NaT
45    SUSHAN S POOJARY  Critical        2026-09-04
53     UTHSAV N SHETTY  Critical        2026-09-09
62   SANATH S DEVADIGA  Critical        2026-09-04
63            SUSHANTH  Critical        2026-09-04
64            YASHVITH  Critical               NaT

### Section 3: Grouping & Aggregation

In [11]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    student_count=("student_name", "count"),
    avg_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max"),
)

          student_count  avg_attendance  max_consecutive_absences
status
Critical             21       38.333333                        12
Safe                 20       94.400000                         1
Warning              24       80.000000                         1

In [ ]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
def categorize(pct):
  if pct >= 90:
    return "Excellent"
  elif pct >= 75:
    return "Good"
  elif pct >= 60:
    return "Average"
  else:
    return "Poor"
df["attendance_category"] = df["attendance_pct"].apply(categorize)
df.groupby("attendance_category").size().reset_index(name="count")

  attendance_category  count
0             Average      8
1           Excellent     20
2                Good     24
3                Poor     13

In [13]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
df.agg(
    total_classes_conducted=("total_classes", "sum"),
    total_present=("present", "sum"),
    total_absent=("absent", "sum"),
)

                         total_classes  present  absent
total_classes_conducted          779.0      NaN     NaN
total_present                      NaN    553.0     NaN
total_absent                       NaN      NaN   226.0

In [14]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    min_present=("present", "min"),
    max_present=("present", "max"),
    mean_present=("present", "mean"),
    total_absent=("absent", "sum"),
)

          min_present  max_present  mean_present  total_absent
status
Critical            0            8      4.571429           155
Safe               11           12     11.300000            14
Warning             9           10      9.625000            57

### Section 4: Feature Engineering & Transformation

In [15]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)
df.sort_values(by="risk_score", ascending=False)[
    ["student_name", "risk_score"]
].head(10)

          student_name  risk_score
20  SHREEHARI SHENOY R        12.0
64            YASHVITH        12.0
43             SURAJ R        12.0
45    SUSHAN S POOJARY        10.4
62   SANATH S DEVADIGA        10.4
63            SUSHANTH        10.4
53     UTHSAV N SHETTY         9.4
2       SAMEER ACHARYA         5.8
9               SARGAM         5.4
22     SHREESHESHA G A         3.8

In [25]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------

df["classes_needed_numeric"] = (
    df["classes_needed_75pct"].astype(str).str.extract(r"(\d+)").fillna(0).astype(int)
)
df[["classes_needed_75pct", "classes_needed_numeric"]].head()

  classes_needed_75pct  classes_needed_numeric
0                ✓ Met                       0
1                ✓ Met                       0
2              28 more                      28
3                ✓ Met                       0
4                ✓ Met                       0

In [17]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["attendance_flag"] = df["attendance_pct"].apply(
    lambda x: "Defaulter" if x < 75 else "Safe"
)
df[["student_name", "attendance_pct", "attendance_flag"]].head()

      student_name  attendance_pct attendance_flag
0    SAKSHI SHETTY           100.0            Safe
1  SAMEEKSHA BEKAL            92.0            Safe
2   SAMEER ACHARYA            17.0       Defaulter
3    SAMHITA S RAO            75.0            Safe
4         SAMIKSHA            83.0            Safe

In [18]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
bins = [0, 50, 75, 90, 100]
labels = ["Critical", "Warning", "Good", "Excellent"]
df["attendance_bin"] = pd.cut(
    df["attendance_pct"], bins=bins, labels=labels, include_lowest=True
)
df[["student_name", "attendance_pct", "attendance_bin"]].head()

      student_name  attendance_pct attendance_bin
0    SAKSHI SHETTY           100.0      Excellent
1  SAMEEKSHA BEKAL            92.0      Excellent
2   SAMEER ACHARYA            17.0       Critical
3    SAMHITA S RAO            75.0        Warning
4         SAMIKSHA            83.0           Good

### Section 5: Advanced Analysis

In [19]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
pd.pivot_table(
    df,
    index="status",
    columns="attendance_category",
    values="student_name",
    aggfunc="count",
    fill_value=0,
)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   8          0     0    13
Safe                       0         20     0     0
Warning                    0          0    24     0

In [ ]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------

df["base_name"] = (
    df["student_name"].astype(str).str.split("(").str[0].str.strip()
)
duplicates = df[df.duplicated(subset=["base_name"], keep=False)]
duplicates[["student_name", "base_name"]]

                     student_name base_name
23              SHREYA (JAYANTH )    SHREYA
24  SHREYA(SATHYANARAYANA ACHARI)    SHREYA
25  SHREYA(SHIVANANDA MARAKALA G)    SHREYA
26            SHREYA (VIJAYENDRA)    SHREYA
36             SOWJANYA (SUNDARA)  SOWJANYA
37                 SOWJANYA(GURU)  SOWJANYA
46    SUSHANTH (SEETHARAMA ACHAR)  SUSHANTH
63                       SUSHANTH  SUSHANTH

In [ ]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------

details_data = pd.DataFrame({
    "roll_no": df["roll_no"].unique(),
    "branch": "CSE",
    "semester": "3rd",
})
merged_df = pd.merge(df, details_data, on="roll_no", how="inner")
merged_df.head()

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,attendance_category,risk_score,attendance_flag,attendance_bin,base_name,branch,semester
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0,Excellent,0.0,Safe,Excellent,SAKSHI SHETTY,CSE,3rd
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-07,1,Excellent,1.0,Safe,Excellent,SAMEEKSHA BEKAL,CSE,3rd
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3,Poor,5.8,Defaulter,Critical,SAMEER ACHARYA,CSE,3rd
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,0,Good,1.2,Safe,Warning,SAMHITA S RAO,CSE,3rd
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83.0,Warning,✓ Met,2026-10-07,1,Good,1.4,Safe,Good,SAMIKSHA,CSE,3rd

In [ ]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------

df[df["status"] == "Critical"].to_csv("critical_students.csv", index=False)
status_summary = df.groupby("status").agg(
    {"present": "mean", "absent": "sum", "attendance_pct": "mean"}
)
status_summary.to_csv("status_summary.csv")
df.sort_values(by="risk_score", ascending=False) \
  .head(10) \
  .to_csv("top_risk_students.csv", index=False)
print("All files exported successfully!")

All files exported successfully!